# Generated by Django 4.2.4 on 2023-09-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='github',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='website',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
