# Generated by Django 4.2.4 on 2023-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_alter_socialmedia_facebook_alter_socialmedia_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='address_photos')),
                ('toal_roommates', models.IntegerField(default=0)),
            ],
        ),
    ]
