# Generated by Django 4.2.4 on 2023-09-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='toal_roommates',
            new_name='total_roommates',
        ),
    ]
