# Generated by Django 4.2.4 on 2023-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0007_roommatereview_addressreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('author', models.ManyToManyField(to='roommates.userprofile')),
            ],
        ),
    ]
