# Generated by Django 4.2.4 on 2023-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0008_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='author',
            field=models.ManyToManyField(blank=True, to='roommates.userprofile'),
        ),
    ]
