# Generated by Django 4.2.4 on 2023-09-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0013_roommate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roommate',
        ),
    ]
